import {
  // bookings
  ClipboardList,
  Plus,
  Inbox,
  FolderArchive,
  Bug,
  Ticket,
  Link2,
  Lock,
  ScrollText,
  Settings,
  Briefcase,
  // sales / crm
  Target,
  User,
  Sparkles,
  Compass,
  Trophy,
  Tag,
  FileText,
  Map,
  Puzzle,
  // finance
  Receipt,
  Coins,
  BookOpen,
  Landmark,
  RefreshCw,
  ShieldCheck,
  Undo2,
  CreditCard,
  AlarmClock,
  BedDouble,
  FileCheck2,
  Banknote,
  Building2,
  // shared
  Users,
  BarChart3,
  TrendingUp,
  TrendingDown,
  LineChart,
  // messenger
  MessageSquare,
  MessageCircle,
  Radio,
  Brain,
  Megaphone,
  Library,
  Package,
  Phone,
  ShoppingBag,
  // marketing
  Anchor,
  Repeat,
  Bot,
  Gift,
  Palette,
  Clapperboard,
  Tv,
  Globe,
  // studio
  Film,
  Pencil,
  Image as ImageIcon,
  Save,
  // hr / planner
  Calendar,
  Umbrella,
  CalendarDays,
  Folder,
  // homepage problem / why / platform
  FileWarning,
  Hourglass,
  EyeOff,
  DoorOpen,
  Feather,
  Upload,
  Plug,
  Zap,
  Activity,
  Bell,
  Newspaper,
  type LucideIcon,
} from "lucide-react";

// Emoji → Lucide icon map. Both the bare emoji and the
// variation-selector form are included for safety.
const ICON_MAP: Record<string, LucideIcon> = {
  // ── Bookings ──
  "📋": ClipboardList,
  "➕": Plus,
  "📥": Inbox,
  "📊": BarChart3,
  "📈": TrendingUp,
  "📉": TrendingDown,
  "🗂️": FolderArchive,
  "🗂": FolderArchive,
  "🐞": Bug,
  "👥": Users,
  "🎫": Ticket,
  "🔗": Link2,
  "🔒": Lock,
  "📝": ScrollText,
  "⚙️": Settings,
  "⚙": Settings,
  "🧳": Briefcase,
  "📑": FileWarning, // disconnected-tools card on homepage
  // ── Sales / CRM ──
  "🎯": Target,
  "👤": User,
  "🌟": Sparkles,
  "✦": Sparkles,
  "🧭": Compass,
  "🏆": Trophy,
  "🏷️": Tag,
  "🏷": Tag,
  "📄": FileText,
  "🗺️": Map,
  "🗺": Map,
  "🧩": Puzzle,
  // ── Finance ──
  "💼": Briefcase,
  "🧾": Receipt,
  "💰": Coins,
  "📒": BookOpen,
  "🏦": Landmark,
  "🔄": RefreshCw,
  "🛡️": ShieldCheck,
  "🛡": ShieldCheck,
  "↩️": Undo2,
  "↩": Undo2,
  "💳": CreditCard,
  "⏰": AlarmClock,
  "🛌": BedDouble,
  "🏨": Building2,
  "💸": Banknote,
  // ── Messenger ──
  "💬": MessageSquare,
  "💚": MessageCircle,
  "📡": Radio,
  "🧠": Brain,
  "📚": Library,
  "📣": Megaphone,
  "📦": Package,
  "📞": Phone,
  "📷": ImageIcon,
  "🛒": ShoppingBag,
  // ── Marketing ──
  "🪝": Anchor,
  "🔁": Repeat,
  "🤖": Bot,
  "🎁": Gift,
  "🎨": Palette,
  "🎬": Clapperboard,
  "📺": Tv,
  "🌐": Globe,
  "📘": MessageCircle, // Facebook lead-ads
  // ── Studio ──
  "🎞️": Film,
  "🎞": Film,
  "✏️": Pencil,
  "✏": Pencil,
  "✍️": Pencil,
  "✍": Pencil,
  "🖼️": ImageIcon,
  "🖼": ImageIcon,
  "💾": Save,
  // ── HR / Planner ──
  "📅": Calendar,
  "🏖️": Umbrella,
  "🏖": Umbrella,
  "🗓️": CalendarDays,
  "🗓": CalendarDays,
  "📁": Folder,
  // ── Homepage problem ──
  "⏳": Hourglass,
  "🤐": EyeOff,
  "🚪": DoorOpen,
  // ── Why-Becko / Platform ──
  "🪶": Feather,
  "📤": Upload,
  "🔌": Plug,
  "⚡": Zap,
  "🚦": Activity,
  "🔔": Bell,
  "📰": Newspaper,
};

export function getIcon(emoji: string | undefined | null): LucideIcon | null {
  if (!emoji) return null;
  return ICON_MAP[emoji] ?? null;
}
